Repository cobaltcore-dev/aurora-dashboard, pull requests merged in 2025-07, with the labels that each got.

#266 chore(core): adds missing permissions to workflows
  .github/workflows/ci-title-lint-check.yaml
  .github/workflows/reuse.yaml
Labels: cd/ci

#267 fix(ui): prevent loading spinner from showing on search parameter changes
  apps/aurora-portal/src/client/routes/__root.tsx
Labels: bug, aurora-portal

#340 research(core): create Proposal for Integrating tRPC Subscriptions in BFF Layer
  apps/aurora-portal/docs/004_proposal_subscriptions.md
Labels: research
